# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
